language: python
python:
    - 2.7

sudo: false
dist: trusty
matrix:
    fast_finish: true
env:
    global:
        # possibly different versions in the future
        - IGRAPH=0.7.1
    matrix:
        - NUMPY=1.10 SCIPY=0.16 CYTHON=0.23
        - NUMPY=1.11 SCIPY=0.17 CYTHON=0.24
        - NUMPY=1.12 SCIPY=0.18 CYTHON=0.25
        - NUMPY=1.13 SCIPY=0.19 CYTHON=0.26
addons:
    apt:
        packages:
            - libatlas-dev
            - libatlas-base-dev
            - liblapack-dev
            - gfortran
cache:
    directories:
        - $HOME/igraph

before_install:
    # no igraph (>=0.7) package available for Ubuntu 14.04 LTS
    - bash tools/install-igraph.sh
    - export PATH="$HOME/igraph:$PATH"
    - export PKG_CONFIG_PATH="$HOME/igraph/lib/pkgconfig:$PKG_CONFIG_PATH"
    - export LD_LIBRARY_PATH="$HOME/igraph/lib:$LD_LIBRARY_PATH"
    - ls -R $HOME/igraph

    # current python packages via miniconda
    - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then export MINICONDA=""; else export MINICONDA="3"; fi
    - travis_retry wget http://repo.continuum.io/miniconda/Miniconda$MINICONDA-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"; hash -r
    - conda config --set always_yes yes --set changeps1 no
    - travis_retry conda update -q conda
    - conda info -a

install:
    # test environment
    - travis_retry conda create -q -n test-env python=$TRAVIS_PYTHON_VERSION
    - source activate test-env
    # https://github.com/conda/conda/issues/1367
    - travis_retry conda install -q virtualenv

    # runtime dependencies
    - travis_retry conda install numpy=$NUMPY scipy=$SCIPY cython=$CYTHON

    # testing dependencies
    - travis_retry conda install -q networkx matplotlib basemap sphinx pytest
    - travis_retry pip   install -q tox pytest-xdist pytest-flake8 pylint

before_script:
    # limit py.test processes within container environment
    - sed 's/auto/2/' pytest.ini > temp && mv temp pytest.ini

script:
    # run test suite in dev env
    - pip install -r requirements.txt -e .
    - tox

    # run cleanup script
    - ./tools/publish 1 0 0 1; export DIST="$(basename `ls ../pyunicorn-*` .tar.gz)"; cd ..; tar xzf $DIST.tar.gz; cd $DIST

    # run test suite in source distribution (without Cython)
    - conda uninstall -q cython
    - python setup.py sdist; cd dist; tar xzf $DIST.tar.gz; cd $DIST
    - tox -e doctest,units

notifications:
    email:
        on_success: change
        on_failure: always
